### ISSUE TITLE
Can I create dynamic product link using this library?

### ISSUE THREAD

**Issue by Prottoy2938** [teamtofu/affiliate#10]
Is it possible to create an AWS affiliate link with a specified product name (like **cheese**) programmatically/dynamically?

What are my options? Can I do this using this library?

**Comment by teamtofu** [comment]
Hi Prottoy,

I would implore you to look into the dynamic transformation docs on affiliate.js.org. You could look into Amazon's search query parameter and link a referred link to that.

**Comment by teamtofu** [comment]
This library is platform agnostic and does not talk to Amazon's Product API.
